Architecture
DKARAGODIN/sdicli pull request #1
Opened 2023-02-20 11:24 UTC by DKARAGODIN

2023-02-24 16:28 UTC, uncerso requested changes
Нужно больше подробностей. По вашему описанию любой здравомыслящий программист должен смочь написать программу, не продумывая архитектурных моментов.

Помимо точечных комментариев ещё хочется увидеть:
1) Что из себя допустимый ввод представляет (в какой-нибудь нотации).
2) Коды возврата команд, сейчас они не обрабатываются.

2023-02-24 16:28 UTC, uncerso commented on README.md
> +Если файлы не указаны, тогда команда перенаправляет содержимое входящего ридера в исходящий ридер.
А что такое "файл"? Аргумент является файлом? Он кодирует файл? Может аргумент является путём до файла в фс? А откуда этот путь отсчитывается?

2023-02-24 16:28 UTC, uncerso commented on README.md
> +Если файлы не указаны, тогда команда выводит количество строк, слов и байт в данных входящего ридера.
А формат выходного текста можно увидеть?

2023-02-24 16:28 UTC, uncerso commented on README.md
> +Execute выполняет произвольную команду. На вход команде передаются аргументы. Стандартный потоки входа читает данные из
```suggestion
Execute выполняет произвольную команду. На вход команде передаются аргументы. Стандартный поток входа читает данные из
```

2023-02-24 16:28 UTC, uncerso commented on README.md
> +Команда завершает работу интерпретатора.
А как оно это делает? Отключением питания машины?

2023-02-24 16:28 UTC, uncerso commented on README.md
> + ## Разделение на этапы
```suggestion
## Разделение на этапы
```

2023-02-24 16:28 UTC, uncerso commented on README.md
> + ## Разделение на этапы
Разделение *чего* и на *какие* этапы?

2023-02-24 16:28 UTC, uncerso commented on README.md
> + * В результате работы парсера на базовом этапе будем анализировать только первую команду, игнорируя лексемы после pipe. Итоговый список методов будет состоять из одного элемента.
Что за базовый этап?

2023-02-25 18:34 UTC, DKARAGODIN commented on README.md
> +После выполнения всех команд Runner считывает информацию из последнего исходящего ридера, и отправляет ее на консоль.
"Много вообще не про Runner. Особенно забавно выглядят фразы "а могут не использовать". - именно так. Следующим же предложение указано, что это детали реализации конкретной программы. Т.е. это часть интерфейса, но как им пользоваться команда решает сама.

В целом немного переработал этот абзац. Добавил информацию о последовательном запуске команд с переброской ридеров.

Команды не умеют писать в stderr

2023-02-25 18:34 UTC, DKARAGODIN commented on README.md
> +Runner проверяет результативность выполнения команды. Если в ходе работы команды было выброшено исключение, то оно
Исправлено

2023-02-25 18:35 UTC, DKARAGODIN commented on README.md
> +Если файлы не указаны, тогда команда перенаправляет содержимое входящего ридера в исходящий ридер.
Доработал

2023-02-25 18:35 UTC, DKARAGODIN commented on README.md
> +Если файлы не указаны, тогда команда выводит количество строк, слов и байт в данных входящего ридера.
Добавил

2023-02-25 18:35 UTC, DKARAGODIN commented on README.md
> +Execute выполняет произвольную команду. На вход команде передаются аргументы. Стандартный потоки входа читает данные из
Исправил

2023-02-25 18:35 UTC, DKARAGODIN commented on README.md
> +Команда завершает работу интерпретатора.
Добавил

2023-03-05 20:43 UTC, bachisheo commented on README.md
> + Выполняет подстановки переменных вида $x. Информация о содержимом переменных хранится в статическом классе окружения (*Enviroment*). Если переменной в окружении нет, то вместо нее будет подставлена
Добавили

2023-03-05 20:43 UTC, bachisheo commented on README.md
> + ## Разделение на этапы
написали подробнее

2023-03-18 18:46 UTC, uncerso approved these changes
Теперь вполне неплохо. Достаточно, чтобы зачесть.

2023-03-18 18:46 UTC, uncerso commented on README.md
> +входящего ридера, а стандартный поток вывода и стандартный поток ошибок записывают данные в исходящий ридер.
> Стандартный поток входа читает данные из входящего ридера

А если входящий ридер null, т.е. не существует?

2023-03-18 18:46 UTC, uncerso commented on README.md
> +```var = "([_A-Za-z][_A-Za-z0-9]*)```
Видимо " лишняя. А ещё несколько сбивает с толку то, что `var =` стоит рядом с регуляркой и выделено одинаково, как будто-бы это не определение "var", а часть самой регулярки. Может `=` делать не моноширинным текстом.

2023-03-18 19:44 UTC, merged